name: Feedback
description: Tell us how it went, what worked and what did not
labels: ["feedback"]
body:
  - type: dropdown
    id: tool
    attributes:
      label: Which tool?
      options:
        - OVL portal
        - SEAScope
        - SEAShot
        - The manual
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Your feedback
    validations:
      required: true
